#!/bin/bash
echo -n "The time and date are: "
date
echo "Let's see who's logged into the system: "
who
echo "User info for userid: $USER"
echo UID:$UID
echo HOME:$HOME

testing=$(date)
echo "The date and time are: " $testing

today=$(date +%y%m%d)
ls /usr/bin -al > log.$today

var1=$(echo "scale=4; 3.44 / 5" | bc)
echo The answer is $var1

echo $
